# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# position controller
rf_state_controller:
  type: position_controllers/JointPositionController
  joint: RF_joint
  pid: { p: 1.0, i: 0.1, d: 0.1, i_clamp: 100 }
